---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ruby-app-agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols:
          http:
    processors:
    exporters:
      otlp:
        endpoint: "otel-collector-svc.default.svc.cluster.local:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruby-app
  name: ruby-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-app
  strategy: {}
  template:
    metadata:
      labels:
        app: ruby-app
    spec:
      containers:
      - image: smehrens/ruby-app
        name: ruby-app
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "host.name=$(NODE_NAME)"
      - image: nginx
        name: nginx
        command:
        - "sh"
        - "-c"
        - "while true; do curl -s http://localhost:3000/rolldice; sleep 1; done"
      - image: otel/opentelemetry-collector
        name: agent
        args:
        - --config=/conf/agent.yaml
        env:
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        volumeMounts:
        - mountPath: /conf
          name: agent-config
      volumes:
       - configMap:
           items:
           - key: agent.yaml
             path: agent.yaml
           name: ruby-app-agent-config
         name: agent-config
      tolerations:
      - key: "tier"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"