---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-app-agent-config
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
    exporters:
      otlp:
        endpoint: "otel-collector-svc.default.svc.cluster.local:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - image: smehrens/nodejs-app
        name: nodejs-app
        env:
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "nodejs-app"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=$(DD_ENV),service.name=$(DD_SERVICE)"
      - image: nginx
        name: nginx
        command:
        - "sh"
        - "-c"
        - "while true; do curl -s http://localhost:8080/rolldice; sleep 1; done"
      - image: otel/opentelemetry-collector
        name: agent
        args:
        - --config=/conf/agent.yaml
        env:
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        volumeMounts:
        - mountPath: /conf
          name: agent-config
      volumes:
       - configMap:
           items:
           - key: agent.yaml
             path: agent.yaml
           name: nodejs-app-agent-config
         name: agent-config
      tolerations:
      - key: "tier"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"